global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'reservehub'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['reservehub-latest.onrender.com']
    tls_config:
      insecure_skip_verify: false