sonar.projectKey=reserve-hub_reservehub-backend
sonar.organization=reserve-hub
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/mapper/**,**/ReservehubApplication.java
sonar.architecture.enabled=false
sonar.sca.enabled=false
