spring.application.name=reservehub

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.jwt.secret=${APP_JWT_SECRET:reservehub-dev-default-key-not-for-production-please-use-env-var}
app.jwt.expiration-ms=86400000



spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080


management.endpoints.web.exposure.include=health,prometheus,info,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=reservehub
management.actuator.token=${ACTUATOR_TOKEN:reservehub-metrics-token-local}