-- ============================================================
-- ReserveHub - Schema SQL para Supabase / PostgreSQL
-- Sprint 1 + Sprint 2
-- ============================================================

-- Enum para los roles de usuario
CREATE TYPE user_role AS ENUM ('CLIENTE', 'PROVEEDOR', 'ADMINISTRADOR');

-- Tabla de usuarios (clientes, proveedores y administradores)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    service_type VARCHAR(100),       -- Solo aplica si role es 'PROVEEDOR'
    service_description TEXT,        -- Descripcion extendida, solo 'PROVEEDOR'
    role user_role NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

-- Tabla de códigos de proveedores (para verificar al registrar un proveedor)
CREATE TABLE provider_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    used BOOLEAN NOT NULL DEFAULT false,
    active BOOLEAN NOT NULL DEFAULT true  -- HU-09: el admin puede desactivar sin consumir
);

-- ============================================================
-- Sprint 2
-- ============================================================

-- Tabla de franjas de disponibilidad (HU-06, HU-07)
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    available_slots INTEGER NOT NULL CHECK (available_slots >= 0),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_end_after_start CHECK (end_time > start_time)
);

CREATE INDEX idx_schedules_provider ON schedules(provider_id);
CREATE INDEX idx_schedules_start_time ON schedules(start_time);
CREATE INDEX idx_schedules_active ON schedules(active);

-- Enum para el estado de una reserva
CREATE TYPE booking_status AS ENUM ('CONFIRMED', 'CANCELLED');

-- Tabla de reservas (HU-08)
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
    status booking_status NOT NULL DEFAULT 'CONFIRMED',
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bookings_client ON bookings(client_id);
CREATE INDEX idx_bookings_schedule ON bookings(schedule_id);
