-- Enum para los roles de usuario
CREATE TYPE user_role AS ENUM ('CLIENTE', 'PROVEEDOR', 'ADMINISTRADOR');

-- Tabla de usuarios (clientes, proveedores y administradores)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    service_type VARCHAR(100), -- Solo aplica si role es 'PROVEEDOR'
    service_description TEXT,  -- Descripcion extendida, solo 'PROVEEDOR'
    role user_role NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

-- Tabla de códigos de proveedores (para verificar al registrar un proveedor)
CREATE TABLE provider_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    used BOOLEAN NOT NULL DEFAULT false
);
